(define (domain grounded-STRIPS-TPP-PROPOSITIONALPREFERENCES)
(:requirements
:strips
)
(:predicates
(AT-TRUCK1-MARKET1)
(AT-TRUCK2-MARKET1)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(STORED-GOODS1-LEVEL1)
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(STORED-GOODS1-LEVEL2)
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL3)
(LOADED-GOODS1-TRUCK2-LEVEL3)
(LOADED-GOODS2-TRUCK1-LEVEL3)
(LOADED-GOODS2-TRUCK2-LEVEL3)
(STORED-GOODS1-LEVEL3)
(STORED-GOODS2-LEVEL3)
(STORED-GOODS2-LEVEL0)
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS2-TRUCK2-LEVEL0)
(LOADED-GOODS2-TRUCK1-LEVEL0)
(LOADED-GOODS1-TRUCK2-LEVEL0)
(LOADED-GOODS1-TRUCK1-LEVEL0)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(AT-TRUCK2-DEPOT1)
(AT-TRUCK1-DEPOT1)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL0)
(LOADED-GOODS2-TRUCK2-LEVEL3)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL2)
(STORED-GOODS2-LEVEL1)
(not (LOADED-GOODS2-TRUCK2-LEVEL3))
(not (STORED-GOODS2-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL0)
(LOADED-GOODS2-TRUCK1-LEVEL3)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL2)
(STORED-GOODS2-LEVEL1)
(not (LOADED-GOODS2-TRUCK1-LEVEL3))
(not (STORED-GOODS2-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS1-TRUCK2-LEVEL3)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL2)
(STORED-GOODS1-LEVEL1)
(not (LOADED-GOODS1-TRUCK2-LEVEL3))
(not (STORED-GOODS1-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS1-TRUCK1-LEVEL3)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL2)
(STORED-GOODS1-LEVEL1)
(not (LOADED-GOODS1-TRUCK1-LEVEL3))
(not (STORED-GOODS1-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL3)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL2)
(STORED-GOODS2-LEVEL2)
(not (LOADED-GOODS2-TRUCK2-LEVEL3))
(not (STORED-GOODS2-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL3)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL2)
(STORED-GOODS2-LEVEL2)
(not (LOADED-GOODS2-TRUCK1-LEVEL3))
(not (STORED-GOODS2-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL3)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL2)
(STORED-GOODS1-LEVEL2)
(not (LOADED-GOODS1-TRUCK2-LEVEL3))
(not (STORED-GOODS1-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL3)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL2)
(STORED-GOODS1-LEVEL2)
(not (LOADED-GOODS1-TRUCK1-LEVEL3))
(not (STORED-GOODS1-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL0)
(STORED-GOODS2-LEVEL3)
(not (LOADED-GOODS2-TRUCK2-LEVEL1))
(not (STORED-GOODS2-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL0)
(STORED-GOODS2-LEVEL3)
(not (LOADED-GOODS2-TRUCK1-LEVEL1))
(not (STORED-GOODS2-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL0)
(STORED-GOODS1-LEVEL3)
(not (LOADED-GOODS1-TRUCK2-LEVEL1))
(not (STORED-GOODS1-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL0)
(STORED-GOODS1-LEVEL3)
(not (LOADED-GOODS1-TRUCK1-LEVEL1))
(not (STORED-GOODS1-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL1)
(STORED-GOODS2-LEVEL3)
(not (LOADED-GOODS2-TRUCK2-LEVEL2))
(not (STORED-GOODS2-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL1)
(STORED-GOODS2-LEVEL3)
(not (LOADED-GOODS2-TRUCK1-LEVEL2))
(not (STORED-GOODS2-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL1)
(STORED-GOODS1-LEVEL3)
(not (LOADED-GOODS1-TRUCK2-LEVEL2))
(not (STORED-GOODS1-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL1)
(STORED-GOODS1-LEVEL3)
(not (LOADED-GOODS1-TRUCK1-LEVEL2))
(not (STORED-GOODS1-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL3)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL2)
(STORED-GOODS2-LEVEL3)
(not (LOADED-GOODS2-TRUCK2-LEVEL3))
(not (STORED-GOODS2-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL3)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL2)
(STORED-GOODS2-LEVEL3)
(not (LOADED-GOODS2-TRUCK1-LEVEL3))
(not (STORED-GOODS2-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL3)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL2)
(STORED-GOODS1-LEVEL3)
(not (LOADED-GOODS1-TRUCK2-LEVEL3))
(not (STORED-GOODS1-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL3)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL2)
(STORED-GOODS1-LEVEL3)
(not (LOADED-GOODS1-TRUCK1-LEVEL3))
(not (STORED-GOODS1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(LOADED-GOODS2-TRUCK2-LEVEL0)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (LOADED-GOODS2-TRUCK2-LEVEL0))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(LOADED-GOODS2-TRUCK1-LEVEL0)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (LOADED-GOODS2-TRUCK1-LEVEL0))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(LOADED-GOODS1-TRUCK2-LEVEL0)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (LOADED-GOODS1-TRUCK2-LEVEL0))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(LOADED-GOODS1-TRUCK1-LEVEL0)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL1)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (LOADED-GOODS1-TRUCK1-LEVEL0))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (LOADED-GOODS2-TRUCK2-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (LOADED-GOODS2-TRUCK1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (LOADED-GOODS1-TRUCK2-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (LOADED-GOODS1-TRUCK1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(not (LOADED-GOODS2-TRUCK2-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(not (LOADED-GOODS2-TRUCK1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(not (LOADED-GOODS1-TRUCK2-LEVEL2))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(not (LOADED-GOODS1-TRUCK1-LEVEL2))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (LOADED-GOODS2-TRUCK2-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (LOADED-GOODS2-TRUCK1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (LOADED-GOODS1-TRUCK2-LEVEL2))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (LOADED-GOODS1-TRUCK1-LEVEL2))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (LOADED-GOODS2-TRUCK2-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL3)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (LOADED-GOODS2-TRUCK1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (LOADED-GOODS1-TRUCK2-LEVEL2))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL3))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL3)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (LOADED-GOODS1-TRUCK1-LEVEL2))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL3))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL0)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL1)
(STORED-GOODS2-LEVEL1)
(not (LOADED-GOODS2-TRUCK2-LEVEL2))
(not (STORED-GOODS2-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL0)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL1)
(STORED-GOODS2-LEVEL1)
(not (LOADED-GOODS2-TRUCK1-LEVEL2))
(not (STORED-GOODS2-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL1)
(STORED-GOODS1-LEVEL1)
(not (LOADED-GOODS1-TRUCK2-LEVEL2))
(not (STORED-GOODS1-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL1)
(STORED-GOODS1-LEVEL1)
(not (LOADED-GOODS1-TRUCK1-LEVEL2))
(not (STORED-GOODS1-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL0)
(STORED-GOODS2-LEVEL2)
(not (LOADED-GOODS2-TRUCK2-LEVEL1))
(not (STORED-GOODS2-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL0)
(STORED-GOODS2-LEVEL2)
(not (LOADED-GOODS2-TRUCK1-LEVEL1))
(not (STORED-GOODS2-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL0)
(STORED-GOODS1-LEVEL2)
(not (LOADED-GOODS1-TRUCK2-LEVEL1))
(not (STORED-GOODS1-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL0)
(STORED-GOODS1-LEVEL2)
(not (LOADED-GOODS1-TRUCK1-LEVEL1))
(not (STORED-GOODS1-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL2)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL1)
(STORED-GOODS2-LEVEL2)
(not (LOADED-GOODS2-TRUCK2-LEVEL2))
(not (STORED-GOODS2-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL2)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL1)
(STORED-GOODS2-LEVEL2)
(not (LOADED-GOODS2-TRUCK1-LEVEL2))
(not (STORED-GOODS2-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL2)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL1)
(STORED-GOODS1-LEVEL2)
(not (LOADED-GOODS1-TRUCK2-LEVEL2))
(not (STORED-GOODS1-LEVEL1))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL2)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL1)
(STORED-GOODS1-LEVEL2)
(not (LOADED-GOODS1-TRUCK1-LEVEL2))
(not (STORED-GOODS1-LEVEL1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(not (ON-SALE-GOODS2-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(not (ON-SALE-GOODS2-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS1-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(not (ON-SALE-GOODS1-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS1-MARKET1-LEVEL3-LEVEL1-LEVEL2-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL3)
(not (ON-SALE-GOODS1-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(not (ON-SALE-GOODS2-MARKET1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL3-LEVEL2-LEVEL2-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(not (ON-SALE-GOODS2-MARKET1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(not (ON-SALE-GOODS2-MARKET1-LEVEL3))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL3-LEVEL3-LEVEL2-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL3)
(not (ON-SALE-GOODS2-MARKET1-LEVEL3))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL0)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (LOADED-GOODS2-TRUCK2-LEVEL0))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL0)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (LOADED-GOODS2-TRUCK1-LEVEL0))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL0)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (LOADED-GOODS1-TRUCK2-LEVEL0))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL0)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL1)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (LOADED-GOODS1-TRUCK1-LEVEL0))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(not (LOADED-GOODS2-TRUCK2-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(not (LOADED-GOODS2-TRUCK1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(not (LOADED-GOODS1-TRUCK2-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(not (LOADED-GOODS1-TRUCK1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (LOADED-GOODS2-TRUCK2-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (LOADED-GOODS2-TRUCK1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (LOADED-GOODS1-TRUCK2-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL2)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (LOADED-GOODS1-TRUCK1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL2))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL0)
(LOADED-GOODS2-TRUCK2-LEVEL1)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL0)
(STORED-GOODS2-LEVEL1)
(not (LOADED-GOODS2-TRUCK2-LEVEL1))
(not (STORED-GOODS2-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS2-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS2-LEVEL0)
(LOADED-GOODS2-TRUCK1-LEVEL1)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL0)
(STORED-GOODS2-LEVEL1)
(not (LOADED-GOODS2-TRUCK1-LEVEL1))
(not (STORED-GOODS2-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS1-TRUCK2-LEVEL1)
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL0)
(STORED-GOODS1-LEVEL1)
(not (LOADED-GOODS1-TRUCK2-LEVEL1))
(not (STORED-GOODS1-LEVEL0))
)
)
(:action UNLOAD-DEPOT1-GOODS1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(STORED-GOODS1-LEVEL0)
(LOADED-GOODS1-TRUCK1-LEVEL1)
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL0)
(STORED-GOODS1-LEVEL1)
(not (LOADED-GOODS1-TRUCK1-LEVEL1))
(not (STORED-GOODS1-LEVEL0))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (ON-SALE-GOODS2-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (ON-SALE-GOODS2-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS1-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (ON-SALE-GOODS1-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS1-MARKET1-LEVEL2-LEVEL1-LEVEL1-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL2)
(not (ON-SALE-GOODS1-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (ON-SALE-GOODS2-MARKET1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL2-LEVEL2-LEVEL1-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (ON-SALE-GOODS2-MARKET1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (ON-SALE-GOODS2-MARKET1-LEVEL3))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL2-LEVEL3-LEVEL1-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL2)
(not (ON-SALE-GOODS2-MARKET1-LEVEL3))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(LOADED-GOODS2-TRUCK2-LEVEL0)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(not (LOADED-GOODS2-TRUCK2-LEVEL0))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS2-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(LOADED-GOODS2-TRUCK1-LEVEL0)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS2-TRUCK1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(not (LOADED-GOODS2-TRUCK1-LEVEL0))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK2-LEVEL0)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK2-LEVEL1)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(not (LOADED-GOODS1-TRUCK2-LEVEL0))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action LOAD-GOODS1-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(LOADED-GOODS1-TRUCK1-LEVEL0)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(LOADED-GOODS1-TRUCK1-LEVEL1)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(not (LOADED-GOODS1-TRUCK1-LEVEL0))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL1))
)
)
(:action DRIVE-DEPOT1-MARKET1-TRUCK2-0
:parameters ()
:precondition
(and
(AT-TRUCK2-MARKET1)
)
:effect
(and
(AT-TRUCK2-DEPOT1)
(not (AT-TRUCK2-MARKET1))
)
)
(:action DRIVE-DEPOT1-MARKET1-TRUCK1-0
:parameters ()
:precondition
(and
(AT-TRUCK1-MARKET1)
)
:effect
(and
(AT-TRUCK1-DEPOT1)
(not (AT-TRUCK1-MARKET1))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (ON-SALE-GOODS2-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (ON-SALE-GOODS2-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS1-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (ON-SALE-GOODS1-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS1-MARKET1-LEVEL1-LEVEL1-LEVEL0-LEVEL0-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL0)
(ON-SALE-GOODS1-MARKET1-LEVEL1)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS1-MARKET1-LEVEL0)
(READY-TO-LOAD-GOODS1-MARKET1-LEVEL1)
(not (ON-SALE-GOODS1-MARKET1-LEVEL1))
(not (READY-TO-LOAD-GOODS1-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (ON-SALE-GOODS2-MARKET1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL1-LEVEL2-LEVEL0-LEVEL1-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL1)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (ON-SALE-GOODS2-MARKET1-LEVEL2))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK2-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(AT-TRUCK2-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (ON-SALE-GOODS2-MARKET1-LEVEL3))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL0))
)
)
(:action BUY-GOODS2-MARKET1-LEVEL1-LEVEL3-LEVEL0-LEVEL2-TRUCK1-0
:parameters ()
:precondition
(and
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL0)
(ON-SALE-GOODS2-MARKET1-LEVEL3)
(AT-TRUCK1-MARKET1)
)
:effect
(and
(ON-SALE-GOODS2-MARKET1-LEVEL2)
(READY-TO-LOAD-GOODS2-MARKET1-LEVEL1)
(not (ON-SALE-GOODS2-MARKET1-LEVEL3))
(not (READY-TO-LOAD-GOODS2-MARKET1-LEVEL0))
)
)
(:action DRIVE-MARKET1-DEPOT1-TRUCK2-0
:parameters ()
:precondition
(and
(AT-TRUCK2-DEPOT1)
)
:effect
(and
(AT-TRUCK2-MARKET1)
(not (AT-TRUCK2-DEPOT1))
)
)
(:action DRIVE-MARKET1-DEPOT1-TRUCK1-0
:parameters ()
:precondition
(and
(AT-TRUCK1-DEPOT1)
)
:effect
(and
(AT-TRUCK1-MARKET1)
(not (AT-TRUCK1-DEPOT1))
)
)
)
