(define (problem tpp)
(:domain tpp-propositionalpreferences)
(:objects truck1 - truck goods1 - goods goods2 - goods truck2 - truck depot1 - depot level0 - level level1 - level level2 - level level3 - level market1 - market)
(:init
	(next level1 level0)
	(next level2 level1)
	(next level3 level2)
	(ready-to-load goods1 market1 level0)
	(ready-to-load goods1 depot1 level0)
	(ready-to-load goods2 market1 level0)
	(ready-to-load goods2 depot1 level0)
	(stored goods1 level0)
	(stored goods2 level0)
	(loaded goods1 truck1 level0)
	(loaded goods1 truck2 level0)
	(loaded goods2 truck1 level0)
	(loaded goods2 truck2 level0)
	(connected depot1 market1)
	(connected market1 depot1)
	(on-sale goods1 market1 level1)
	(on-sale goods2 market1 level3)
	(at truck1 depot1)
	(at truck2 depot1))
(:goal (and (stored goods1 level1) (stored goods2 level3)))
)
