(define (problem tpp)
(:domain tpp-propositionalpreferences)
(:objects
	goods1 goods2 goods3 goods4 goods5 goods6 goods7 goods8 - goods
	truck1 truck2 - truck
	market1 market2 - market
	depot1 - depot
	level0 level1 level2 level3 level4 - level)

(:init
	(next level1 level0)
	(next level2 level1)
	(next level3 level2)
	(next level4 level3)
	(ready-to-load goods1 market1 level0)
	(ready-to-load goods1 market2 level0)
	(ready-to-load goods1 depot1 level0)
	(ready-to-load goods2 market1 level0)
	(ready-to-load goods2 market2 level0)
	(ready-to-load goods2 depot1 level0)
	(ready-to-load goods3 market1 level0)
	(ready-to-load goods3 market2 level0)
	(ready-to-load goods3 depot1 level0)
	(ready-to-load goods4 market1 level0)
	(ready-to-load goods4 market2 level0)
	(ready-to-load goods4 depot1 level0)
	(ready-to-load goods5 market1 level0)
	(ready-to-load goods5 market2 level0)
	(ready-to-load goods5 depot1 level0)
	(ready-to-load goods6 market1 level0)
	(ready-to-load goods6 market2 level0)
	(ready-to-load goods6 depot1 level0)
	(ready-to-load goods7 market1 level0)
	(ready-to-load goods7 market2 level0)
	(ready-to-load goods7 depot1 level0)
	(ready-to-load goods8 market1 level0)
	(ready-to-load goods8 market2 level0)
	(ready-to-load goods8 depot1 level0)
	(stored goods1 level0)
	(stored goods2 level0)
	(stored goods3 level0)
	(stored goods4 level0)
	(stored goods5 level0)
	(stored goods6 level0)
	(stored goods7 level0)
	(stored goods8 level0)
	(loaded goods1 truck1 level0)
	(loaded goods1 truck2 level0)
	(loaded goods2 truck1 level0)
	(loaded goods2 truck2 level0)
	(loaded goods3 truck1 level0)
	(loaded goods3 truck2 level0)
	(loaded goods4 truck1 level0)
	(loaded goods4 truck2 level0)
	(loaded goods5 truck1 level0)
	(loaded goods5 truck2 level0)
	(loaded goods6 truck1 level0)
	(loaded goods6 truck2 level0)
	(loaded goods7 truck1 level0)
	(loaded goods7 truck2 level0)
	(loaded goods8 truck1 level0)
	(loaded goods8 truck2 level0)
	(connected market1 market2)
	(connected market2 market1)
	(connected depot1 market1)
	(connected market1 depot1)
	(connected depot1 market2)
	(connected market2 depot1)
	(on-sale goods1 market1 level3)
	(on-sale goods2 market1 level2)
	(on-sale goods3 market1 level2)
	(on-sale goods4 market1 level4)
	(on-sale goods5 market1 level1)
	(on-sale goods6 market1 level1)
	(on-sale goods7 market1 level2)
	(on-sale goods8 market1 level1)
	(on-sale goods1 market2 level0)
	(on-sale goods2 market2 level2)
	(on-sale goods3 market2 level0)
	(on-sale goods4 market2 level0)
	(on-sale goods5 market2 level3)
	(on-sale goods6 market2 level1)
	(on-sale goods7 market2 level0)
	(on-sale goods8 market2 level0)
	(at truck1 depot1)
	(at truck2 depot1))
(:goal (and
	(stored goods1 level1)
	(stored goods2 level3)
	(stored goods3 level1)
	(stored goods4 level2)
	(stored goods5 level2)
	(stored goods6 level1)
	(stored goods7 level2)
	(stored goods8 level1)))
(:constraints
(and

(forall (?m - market ?t1 ?t2 - truck)(preference p1A (always (imply (and (at ?t1 ?m) (at ?t2 ?m))(= ?t1 ?t2)))))
(preference c1 (always (or (loaded goods2 truck1 level0) (stored goods2 level0) (at truck1 depot1))))
(preference c2 (always (loaded goods2 truck2 level0)))
(preference c3 (always (or (loaded goods4 truck2 level0) (stored goods4 level0) (at truck2 depot1))))
(preference c4 (always (loaded goods4 truck1 level0)))
(preference c5 (always (or (loaded goods5 truck2 level0) (stored goods5 level0) (at truck2 depot1))))
(preference c6 (always (loaded goods5 truck1 level0)))
(preference c7 (always (or (loaded goods7 truck1 level0) (stored goods7 level0) (at truck1 depot1))))
(preference c8 (always (loaded goods7 truck2 level0)))
)
)
(:metric minimize
(+
(* 1 (is-violated p1A))(* 1 (is-violated c4))
(* 1 (is-violated c6))
(* 1 (is-violated c8))
(* 1 (is-violated c7))
(* 1 (is-violated c2))
(* 1 (is-violated c1))
(* 1 (is-violated c3))
(* 1 (is-violated c5))
)
)
)
